apiVersion: v1 
kind: Service
metadata:
  name: kaiburr-app-service
  labels:
     type: app
spec:
   type: NodePort
   ports:
      - targetPort: 8080
        port: 8080
   selector:
       type: app 